### ISSUE TITLE
Clarify license situation

### ISSUE THREAD

**Issue by MightyKnight** [BRForgers/DisFabric#2]
Hey, I just recently heard of your project.

When looking at the Github page, I noticed you don't have a `LICENSE` set.
On Curseforge, it claims to be **All Rights Reserved.**
![grafik](https://user-images.githubusercontent.com/38622942/94494207-e45bd580-01ee-11eb-8440-1d53aa5e1eda.png)

I suggest you clarify what license actually applies to your project. Feel free to choose whatever fits best.

You may also want to read this site on why you shouldn't have no license; https://choosealicense.com/no-permission/
> Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

**Comment by allanf181** [comment]
Fixed
