### ISSUE TITLE
Server not booting

### ISSUE THREAD

**Issue by probablypablito** [BRForgers/DisFabric#45]
My 1.18 server doesn't boot with the mod installed. Works just fine without it. I have tried both 1.18 versions, and compiling from source.
[latest.log](https://github.com/BRForgers/DisFabric/files/7657016/latest.log)

**Comment by allanf181** [comment]
Full log?

**Comment by probablypablito** [comment]
i updated the issue

**Comment by probablypablito** [comment]
god i cant read -- nevermind
