### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Palarista** [BRForgers/DisFabric#46]
Heya! My 1.18 server crashes whenever DisFabric tries to load it seems, even when I've got no other mods aside from Fabric API enabled.
Sorry in advance if it's due to something I missed in the config or something! I do have a channel ID put in the config though.
[crash-2021-12-06_19.41.29-server.txt](https://github.com/BRForgers/DisFabric/files/7662880/crash-2021-12-06_19.41.29-server.txt)
[latest.log](https://github.com/BRForgers/DisFabric/files/7662904/latest.log)

**Comment by allanf181** [comment]
The bot cannot find the channel. It could be wrong ID or the bot doesn't have access to the channel.

**Comment by Palarista** [comment]
Thank you for replying! That's what I thought but I can't seem to figure out how to get it to work, even though before updating to 1.18 it did work.
I'll keep trying!
