### ISSUE TITLE
Users profile picture is Steve when they have a skin

### ISSUE THREAD

**Issue by ElijahRus250** [BRForgers/DisFabric#7]
<img width="314" alt="Screen Shot 2020-12-14 at 1 23 59 PM" src="https://user-images.githubusercontent.com/64851720/102119773-a181c500-3e0f-11eb-8d47-fb9769c64d9b.png">

**Comment by ElijahRus250** [comment]
what do you mean invalid, its a bug

**Comment by allanf181** [comment]
Because it must be a mc-heads.net api problem, not a DisFabric problem.

**Comment by ElijahRus250** [comment]
Well when I go to the site to test the API it’s a normal skin however, it stays as a Steve for like a long time then maybe after a while it will reset
