### ISSUE TITLE
Redirect conflict. Skipping fabric-resource-loader-v0.mixins

### ISSUE THREAD

**Issue by Columbam1998** [BRForgers/DisFabric#78]
Using a java17 based server with the following mods crashes the server 
![image](https://user-images.githubusercontent.com/36681633/211627010-44e2d3d7-7783-488b-a9da-953064936a39.png)
skipping loaders and crashing the server.

[2023-01-10-4.log](https://github.com/BRForgers/DisFabric/files/10385806/2023-01-10-4.log)
log included had to force stop the server due to it

**Comment by Columbam1998** [comment]
seems to be a token broken

**Comment by haykam821** [comment]
DisFabric includes functionality for loading translations on dedicated servers which conflicts with the same feature that Fabric API later added.

**Comment by Columbam1998** [comment]
> 
anyway to fix it? was looking through the log as well and it looks like it's a discord token issue?
