### ISSUE TITLE
webhook can mass ping 

### ISSUE THREAD

**Issue by MrCheeze446** [BRForgers/DisFabric#8]
Please filter out pings, specifically for the webhooks. Without use of webhooks this can be done with role permissions

**Comment by allanf181** [comment]
@everyone?

**Comment by MrCheeze446** [comment]
yeah the webhooks can @everyone, which is an oversight from discord, but if you use the non webhook mode it's alright

**Comment by shayypy** [comment]
not an oversight from discord - but from the mod itself - to be more clear. webhooks are able to send allowed_mentions similar to bots, so i recommend it being used to disable @everyone and @here mentions

**Comment by shayypy** [comment]
i urge you to use [allowed_mentions](https://discord.com/developers/docs/resources/channel#allowed-mentions-object) instead @allanf181; it's the officially supported method from discord (yes, [it works with webhooks](https://discord.com/developers/docs/resources/webhook#execute-webhook)) and is ultimately more reliable than just jamming in a unicode char. i don't know any java, else i'd make a pull request for you. pls consider swapping
