### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by sariyan-0** [BRForgers/DisFabric#82]
My exaroton server is keep crashing after starting and itz keep telling me to remove the mod, can you please tell me what should i do?

**Comment by allanf181** [comment]
log?

**Comment by sariyan-0** [comment]
> log?

https://mclo.gs/rcvobJ5

**Comment by sariyan-0** [comment]
https://mclo.gs/rcvobJ5

**Comment by allanf181** [comment]
You need to enable these intents in your bot
![image](https://github.com/BRForgers/DisFabric/assets/14101716/439dfa3a-2f97-43e2-991e-d1c43ddb05c8)

**Comment by sariyan-0** [comment]
I did and it took 1 minutes to load and as soon as it was about to go online it crashed 

Log: https://mclo.gs/xI6HMT1

**Comment by sariyan-0** [comment]
I did and it took 1 minutes to load and as soon as it was about to go online it crashed

Log: https://mclo.gs/xI6HMT1

**Comment by sariyan-0** [comment]
I did and it took 1 minutes to load and as soon as it was about to go
online it crashed

Log: https://mclo.gs/xI6HMT1

**Comment by sariyan-0** [comment]
Bro answer
