### ISSUE TITLE
Server crashing on startup

### ISSUE THREAD

**Issue by sariyan-0** [BRForgers/DisFabric#83]
Hi when i started  my server it took 1 minutes to load and as soon as it was about to go online it crashed

Log: https://mclo.gs/xI6HMT1

**Comment by allanf181** [comment]
https://www.curseforge.com/minecraft/mc-mods/disfabric/files/4571118
update the mod

**Comment by sariyan-0** [comment]
> https://www.curseforge.com/minecraft/mc-mods/disfabric/files/4571118 update the mod

I did but it started crashing and my client is keep saying to remove the mod

Logs: https://mclo.gs/k1SZpjn
